// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/periodictask/v1/PeriodicTask.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XJson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XJson) Reset() {
	*x = XJson{}
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XJson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XJson) ProtoMessage() {}

func (x *XJson) ProtoReflect() protoreflect.Message {
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XJson.ProtoReflect.Descriptor instead.
func (*XJson) Descriptor() ([]byte, []int) {
	return file_api_periodictask_v1_PeriodicTask_proto_rawDescGZIP(), []int{0}
}

func (x *XJson) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type ServiceRegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRegistryRequest) Reset() {
	*x = ServiceRegistryRequest{}
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegistryRequest) ProtoMessage() {}

func (x *ServiceRegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegistryRequest.ProtoReflect.Descriptor instead.
func (*ServiceRegistryRequest) Descriptor() ([]byte, []int) {
	return file_api_periodictask_v1_PeriodicTask_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceRegistryRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ServiceRegistryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRegistryReply) Reset() {
	*x = ServiceRegistryReply{}
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRegistryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegistryReply) ProtoMessage() {}

func (x *ServiceRegistryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegistryReply.ProtoReflect.Descriptor instead.
func (*ServiceRegistryReply) Descriptor() ([]byte, []int) {
	return file_api_periodictask_v1_PeriodicTask_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceRegistryReply) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type CreatePeriodicTaskQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	QueueName     string                 `protobuf:"bytes,3,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePeriodicTaskQueueRequest) Reset() {
	*x = CreatePeriodicTaskQueueRequest{}
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeriodicTaskQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeriodicTaskQueueRequest) ProtoMessage() {}

func (x *CreatePeriodicTaskQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeriodicTaskQueueRequest.ProtoReflect.Descriptor instead.
func (*CreatePeriodicTaskQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_periodictask_v1_PeriodicTask_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePeriodicTaskQueueRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CreatePeriodicTaskQueueRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *CreatePeriodicTaskQueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type CreatePeriodicTaskQueueReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePeriodicTaskQueueReply) Reset() {
	*x = CreatePeriodicTaskQueueReply{}
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeriodicTaskQueueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeriodicTaskQueueReply) ProtoMessage() {}

func (x *CreatePeriodicTaskQueueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeriodicTaskQueueReply.ProtoReflect.Descriptor instead.
func (*CreatePeriodicTaskQueueReply) Descriptor() ([]byte, []int) {
	return file_api_periodictask_v1_PeriodicTask_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePeriodicTaskQueueReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StartPeriodicTaskQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	QueueName     string                 `protobuf:"bytes,3,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPeriodicTaskQueueRequest) Reset() {
	*x = StartPeriodicTaskQueueRequest{}
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPeriodicTaskQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPeriodicTaskQueueRequest) ProtoMessage() {}

func (x *StartPeriodicTaskQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPeriodicTaskQueueRequest.ProtoReflect.Descriptor instead.
func (*StartPeriodicTaskQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_periodictask_v1_PeriodicTask_proto_rawDescGZIP(), []int{5}
}

func (x *StartPeriodicTaskQueueRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *StartPeriodicTaskQueueRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *StartPeriodicTaskQueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type StartPeriodicTaskQueueReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPeriodicTaskQueueReply) Reset() {
	*x = StartPeriodicTaskQueueReply{}
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPeriodicTaskQueueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPeriodicTaskQueueReply) ProtoMessage() {}

func (x *StartPeriodicTaskQueueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPeriodicTaskQueueReply.ProtoReflect.Descriptor instead.
func (*StartPeriodicTaskQueueReply) Descriptor() ([]byte, []int) {
	return file_api_periodictask_v1_PeriodicTask_proto_rawDescGZIP(), []int{6}
}

func (x *StartPeriodicTaskQueueReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	QueueName     string                 `protobuf:"bytes,3,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	TaskType      string                 `protobuf:"bytes,4,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	TaskData      *XJson                 `protobuf:"bytes,5,opt,name=task_data,json=taskData,proto3" json:"task_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_periodictask_v1_PeriodicTask_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTaskRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CreateTaskRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *CreateTaskRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *CreateTaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *CreateTaskRequest) GetTaskData() *XJson {
	if x != nil {
		return x.TaskData
	}
	return nil
}

type CreateTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskReply) Reset() {
	*x = CreateTaskReply{}
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskReply) ProtoMessage() {}

func (x *CreateTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskReply.ProtoReflect.Descriptor instead.
func (*CreateTaskReply) Descriptor() ([]byte, []int) {
	return file_api_periodictask_v1_PeriodicTask_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTaskReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetTaskListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	QueueName     string                 `protobuf:"bytes,3,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskListRequest) Reset() {
	*x = GetTaskListRequest{}
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskListRequest) ProtoMessage() {}

func (x *GetTaskListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskListRequest.ProtoReflect.Descriptor instead.
func (*GetTaskListRequest) Descriptor() ([]byte, []int) {
	return file_api_periodictask_v1_PeriodicTask_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskListRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetTaskListRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *GetTaskListRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *GetTaskListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTaskListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskList      *XJson                 `protobuf:"bytes,1,opt,name=task_list,json=taskList,proto3" json:"task_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskListReply) Reset() {
	*x = GetTaskListReply{}
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskListReply) ProtoMessage() {}

func (x *GetTaskListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskListReply.ProtoReflect.Descriptor instead.
func (*GetTaskListReply) Descriptor() ([]byte, []int) {
	return file_api_periodictask_v1_PeriodicTask_proto_rawDescGZIP(), []int{10}
}

func (x *GetTaskListReply) GetTaskList() *XJson {
	if x != nil {
		return x.TaskList
	}
	return nil
}

type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	QueueName     string                 `protobuf:"bytes,3,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	TaskId        uint64                 `protobuf:"varint,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_periodictask_v1_PeriodicTask_proto_rawDescGZIP(), []int{11}
}

func (x *CompleteTaskRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CompleteTaskRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *CompleteTaskRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *CompleteTaskRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CompleteTaskRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CompleteTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskReply) Reset() {
	*x = CompleteTaskReply{}
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskReply) ProtoMessage() {}

func (x *CompleteTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_periodictask_v1_PeriodicTask_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskReply.ProtoReflect.Descriptor instead.
func (*CompleteTaskReply) Descriptor() ([]byte, []int) {
	return file_api_periodictask_v1_PeriodicTask_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteTaskReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_periodictask_v1_PeriodicTask_proto protoreflect.FileDescriptor

const file_api_periodictask_v1_PeriodicTask_proto_rawDesc = "" +
	"\n" +
	"&api/periodictask/v1/PeriodicTask.proto\x12\x13api.periodictask.v1\"\x1b\n" +
	"\x05_Json\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\";\n" +
	"\x16ServiceRegistryRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\".\n" +
	"\x14ServiceRegistryReply\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\"z\n" +
	"\x1eCreatePeriodicTaskQueueRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x03 \x01(\tR\tqueueName\"8\n" +
	"\x1cCreatePeriodicTaskQueueReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"y\n" +
	"\x1dStartPeriodicTaskQueueRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x03 \x01(\tR\tqueueName\"7\n" +
	"\x1bStartPeriodicTaskQueueReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc3\x01\n" +
	"\x11CreateTaskRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x03 \x01(\tR\tqueueName\x12\x1b\n" +
	"\ttask_type\x18\x04 \x01(\tR\btaskType\x127\n" +
	"\ttask_data\x18\x05 \x01(\v2\x1a.api.periodictask.v1._JsonR\btaskData\"+\n" +
	"\x0fCreateTaskReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x84\x01\n" +
	"\x12GetTaskListRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x03 \x01(\tR\tqueueName\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"K\n" +
	"\x10GetTaskListReply\x127\n" +
	"\ttask_list\x18\x01 \x01(\v2\x1a.api.periodictask.v1._JsonR\btaskList\"\xa2\x01\n" +
	"\x13CompleteTaskRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x03 \x01(\tR\tqueueName\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\x04R\x06taskId\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\"-\n" +
	"\x11CompleteTaskReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x9a\x05\n" +
	"\fPeriodicTask\x12i\n" +
	"\x0fServiceRegistry\x12+.api.periodictask.v1.ServiceRegistryRequest\x1a).api.periodictask.v1.ServiceRegistryReply\x12\x81\x01\n" +
	"\x17CreatePeriodicTaskQueue\x123.api.periodictask.v1.CreatePeriodicTaskQueueRequest\x1a1.api.periodictask.v1.CreatePeriodicTaskQueueReply\x12~\n" +
	"\x16StartPeriodicTaskQueue\x122.api.periodictask.v1.StartPeriodicTaskQueueRequest\x1a0.api.periodictask.v1.StartPeriodicTaskQueueReply\x12Z\n" +
	"\n" +
	"CreateTask\x12&.api.periodictask.v1.CreateTaskRequest\x1a$.api.periodictask.v1.CreateTaskReply\x12]\n" +
	"\vGetTaskList\x12'.api.periodictask.v1.GetTaskListRequest\x1a%.api.periodictask.v1.GetTaskListReply\x12`\n" +
	"\fCompleteTask\x12(.api.periodictask.v1.CompleteTaskRequest\x1a&.api.periodictask.v1.CompleteTaskReplyB=\n" +
	"\x13api.periodictask.v1P\x01Z$periodic-task/api/periodictask/v1;v1b\x06proto3"

var (
	file_api_periodictask_v1_PeriodicTask_proto_rawDescOnce sync.Once
	file_api_periodictask_v1_PeriodicTask_proto_rawDescData []byte
)

func file_api_periodictask_v1_PeriodicTask_proto_rawDescGZIP() []byte {
	file_api_periodictask_v1_PeriodicTask_proto_rawDescOnce.Do(func() {
		file_api_periodictask_v1_PeriodicTask_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_periodictask_v1_PeriodicTask_proto_rawDesc), len(file_api_periodictask_v1_PeriodicTask_proto_rawDesc)))
	})
	return file_api_periodictask_v1_PeriodicTask_proto_rawDescData
}

var file_api_periodictask_v1_PeriodicTask_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_periodictask_v1_PeriodicTask_proto_goTypes = []any{
	(*XJson)(nil),                          // 0: api.periodictask.v1._Json
	(*ServiceRegistryRequest)(nil),         // 1: api.periodictask.v1.ServiceRegistryRequest
	(*ServiceRegistryReply)(nil),           // 2: api.periodictask.v1.ServiceRegistryReply
	(*CreatePeriodicTaskQueueRequest)(nil), // 3: api.periodictask.v1.CreatePeriodicTaskQueueRequest
	(*CreatePeriodicTaskQueueReply)(nil),   // 4: api.periodictask.v1.CreatePeriodicTaskQueueReply
	(*StartPeriodicTaskQueueRequest)(nil),  // 5: api.periodictask.v1.StartPeriodicTaskQueueRequest
	(*StartPeriodicTaskQueueReply)(nil),    // 6: api.periodictask.v1.StartPeriodicTaskQueueReply
	(*CreateTaskRequest)(nil),              // 7: api.periodictask.v1.CreateTaskRequest
	(*CreateTaskReply)(nil),                // 8: api.periodictask.v1.CreateTaskReply
	(*GetTaskListRequest)(nil),             // 9: api.periodictask.v1.GetTaskListRequest
	(*GetTaskListReply)(nil),               // 10: api.periodictask.v1.GetTaskListReply
	(*CompleteTaskRequest)(nil),            // 11: api.periodictask.v1.CompleteTaskRequest
	(*CompleteTaskReply)(nil),              // 12: api.periodictask.v1.CompleteTaskReply
}
var file_api_periodictask_v1_PeriodicTask_proto_depIdxs = []int32{
	0,  // 0: api.periodictask.v1.CreateTaskRequest.task_data:type_name -> api.periodictask.v1._Json
	0,  // 1: api.periodictask.v1.GetTaskListReply.task_list:type_name -> api.periodictask.v1._Json
	1,  // 2: api.periodictask.v1.PeriodicTask.ServiceRegistry:input_type -> api.periodictask.v1.ServiceRegistryRequest
	3,  // 3: api.periodictask.v1.PeriodicTask.CreatePeriodicTaskQueue:input_type -> api.periodictask.v1.CreatePeriodicTaskQueueRequest
	5,  // 4: api.periodictask.v1.PeriodicTask.StartPeriodicTaskQueue:input_type -> api.periodictask.v1.StartPeriodicTaskQueueRequest
	7,  // 5: api.periodictask.v1.PeriodicTask.CreateTask:input_type -> api.periodictask.v1.CreateTaskRequest
	9,  // 6: api.periodictask.v1.PeriodicTask.GetTaskList:input_type -> api.periodictask.v1.GetTaskListRequest
	11, // 7: api.periodictask.v1.PeriodicTask.CompleteTask:input_type -> api.periodictask.v1.CompleteTaskRequest
	2,  // 8: api.periodictask.v1.PeriodicTask.ServiceRegistry:output_type -> api.periodictask.v1.ServiceRegistryReply
	4,  // 9: api.periodictask.v1.PeriodicTask.CreatePeriodicTaskQueue:output_type -> api.periodictask.v1.CreatePeriodicTaskQueueReply
	6,  // 10: api.periodictask.v1.PeriodicTask.StartPeriodicTaskQueue:output_type -> api.periodictask.v1.StartPeriodicTaskQueueReply
	8,  // 11: api.periodictask.v1.PeriodicTask.CreateTask:output_type -> api.periodictask.v1.CreateTaskReply
	10, // 12: api.periodictask.v1.PeriodicTask.GetTaskList:output_type -> api.periodictask.v1.GetTaskListReply
	12, // 13: api.periodictask.v1.PeriodicTask.CompleteTask:output_type -> api.periodictask.v1.CompleteTaskReply
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_periodictask_v1_PeriodicTask_proto_init() }
func file_api_periodictask_v1_PeriodicTask_proto_init() {
	if File_api_periodictask_v1_PeriodicTask_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_periodictask_v1_PeriodicTask_proto_rawDesc), len(file_api_periodictask_v1_PeriodicTask_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_periodictask_v1_PeriodicTask_proto_goTypes,
		DependencyIndexes: file_api_periodictask_v1_PeriodicTask_proto_depIdxs,
		MessageInfos:      file_api_periodictask_v1_PeriodicTask_proto_msgTypes,
	}.Build()
	File_api_periodictask_v1_PeriodicTask_proto = out.File
	file_api_periodictask_v1_PeriodicTask_proto_goTypes = nil
	file_api_periodictask_v1_PeriodicTask_proto_depIdxs = nil
}
