// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/user/v1/User.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_user_v1_User_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_api_user_v1_User_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type BindEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindEmailRequest) Reset() {
	*x = BindEmailRequest{}
	mi := &file_api_user_v1_User_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindEmailRequest) ProtoMessage() {}

func (x *BindEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindEmailRequest.ProtoReflect.Descriptor instead.
func (*BindEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{2}
}

func (x *BindEmailRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BindEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type BindEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindEmailReply) Reset() {
	*x = BindEmailReply{}
	mi := &file_api_user_v1_User_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindEmailReply) ProtoMessage() {}

func (x *BindEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindEmailReply.ProtoReflect.Descriptor instead.
func (*BindEmailReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{3}
}

func (x *BindEmailReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BindMobileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindMobileRequest) Reset() {
	*x = BindMobileRequest{}
	mi := &file_api_user_v1_User_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindMobileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMobileRequest) ProtoMessage() {}

func (x *BindMobileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindMobileRequest.ProtoReflect.Descriptor instead.
func (*BindMobileRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{4}
}

func (x *BindMobileRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BindMobileRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type BindMobileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindMobileReply) Reset() {
	*x = BindMobileReply{}
	mi := &file_api_user_v1_User_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindMobileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMobileReply) ProtoMessage() {}

func (x *BindMobileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindMobileReply.ProtoReflect.Descriptor instead.
func (*BindMobileReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{5}
}

func (x *BindMobileReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IDLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDLoginRequest) Reset() {
	*x = IDLoginRequest{}
	mi := &file_api_user_v1_User_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDLoginRequest) ProtoMessage() {}

func (x *IDLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDLoginRequest.ProtoReflect.Descriptor instead.
func (*IDLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{6}
}

func (x *IDLoginRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IDLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type IDLoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDLoginReply) Reset() {
	*x = IDLoginReply{}
	mi := &file_api_user_v1_User_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDLoginReply) ProtoMessage() {}

func (x *IDLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDLoginReply.ProtoReflect.Descriptor instead.
func (*IDLoginReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{7}
}

func (x *IDLoginReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailRequest) Reset() {
	*x = GetEmailRequest{}
	mi := &file_api_user_v1_User_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailRequest) ProtoMessage() {}

func (x *GetEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailRequest.ProtoReflect.Descriptor instead.
func (*GetEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{8}
}

func (x *GetEmailRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailReply) Reset() {
	*x = GetEmailReply{}
	mi := &file_api_user_v1_User_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailReply) ProtoMessage() {}

func (x *GetEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailReply.ProtoReflect.Descriptor instead.
func (*GetEmailReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{9}
}

func (x *GetEmailReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetMobileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMobileRequest) Reset() {
	*x = GetMobileRequest{}
	mi := &file_api_user_v1_User_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMobileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMobileRequest) ProtoMessage() {}

func (x *GetMobileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMobileRequest.ProtoReflect.Descriptor instead.
func (*GetMobileRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{10}
}

func (x *GetMobileRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMobileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMobileReply) Reset() {
	*x = GetMobileReply{}
	mi := &file_api_user_v1_User_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMobileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMobileReply) ProtoMessage() {}

func (x *GetMobileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMobileReply.ProtoReflect.Descriptor instead.
func (*GetMobileReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{11}
}

func (x *GetMobileReply) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_user_v1_User_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReply) Reset() {
	*x = DeleteReply{}
	mi := &file_api_user_v1_User_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReply) ProtoMessage() {}

func (x *DeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReply.ProtoReflect.Descriptor instead.
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_api_user_v1_User_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{14}
}

func (x *UpdatePasswordRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdatePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdatePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdatePasswordReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordReply) Reset() {
	*x = UpdatePasswordReply{}
	mi := &file_api_user_v1_User_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordReply) ProtoMessage() {}

func (x *UpdatePasswordReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordReply.ProtoReflect.Descriptor instead.
func (*UpdatePasswordReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatePasswordReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsernameRequest) Reset() {
	*x = UpdateUsernameRequest{}
	mi := &file_api_user_v1_User_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameRequest) ProtoMessage() {}

func (x *UpdateUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameRequest.ProtoReflect.Descriptor instead.
func (*UpdateUsernameRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateUsernameRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdateUsernameReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsernameReply) Reset() {
	*x = UpdateUsernameReply{}
	mi := &file_api_user_v1_User_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameReply) ProtoMessage() {}

func (x *UpdateUsernameReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_User_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameReply.ProtoReflect.Descriptor instead.
func (*UpdateUsernameReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_User_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateUsernameReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_user_v1_User_proto protoreflect.FileDescriptor

const file_api_user_v1_User_proto_rawDesc = "" +
	"\n" +
	"\x16api/user/v1/User.proto\x12\vapi.user.v1\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"(\n" +
	"\rRegisterReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"A\n" +
	"\x10BindEmailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"*\n" +
	"\x0eBindEmailReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"D\n" +
	"\x11BindMobileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\"+\n" +
	"\x0fBindMobileReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\x0eIDLoginRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"*\n" +
	"\fIDLoginReply\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"*\n" +
	"\x0fGetEmailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"%\n" +
	"\rGetEmailReply\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"+\n" +
	"\x10GetMobileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"(\n" +
	"\x0eGetMobileReply\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\"D\n" +
	"\rDeleteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"'\n" +
	"\vDeleteReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"v\n" +
	"\x15UpdatePasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"/\n" +
	"\x13UpdatePasswordReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"L\n" +
	"\x15UpdateUsernameRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"/\n" +
	"\x13UpdateUsernameReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa3\x05\n" +
	"\x04User\x12D\n" +
	"\bRegister\x12\x1c.api.user.v1.RegisterRequest\x1a\x1a.api.user.v1.RegisterReply\x12G\n" +
	"\tBindEmail\x12\x1d.api.user.v1.BindEmailRequest\x1a\x1b.api.user.v1.BindEmailReply\x12J\n" +
	"\n" +
	"BindMobile\x12\x1e.api.user.v1.BindMobileRequest\x1a\x1c.api.user.v1.BindMobileReply\x12A\n" +
	"\aIDLogin\x12\x1b.api.user.v1.IDLoginRequest\x1a\x19.api.user.v1.IDLoginReply\x12D\n" +
	"\bGetEmail\x12\x1c.api.user.v1.GetEmailRequest\x1a\x1a.api.user.v1.GetEmailReply\x12G\n" +
	"\tGetMobile\x12\x1d.api.user.v1.GetMobileRequest\x1a\x1b.api.user.v1.GetMobileReply\x12>\n" +
	"\x06Delete\x12\x1a.api.user.v1.DeleteRequest\x1a\x18.api.user.v1.DeleteReply\x12V\n" +
	"\x0eUpdatePassword\x12\".api.user.v1.UpdatePasswordRequest\x1a .api.user.v1.UpdatePasswordReply\x12V\n" +
	"\x0eUpdateUsername\x12\".api.user.v1.UpdateUsernameRequest\x1a .api.user.v1.UpdateUsernameReplyB$\n" +
	"\vapi.user.v1P\x01Z\x13user/api/user/v1;v1b\x06proto3"

var (
	file_api_user_v1_User_proto_rawDescOnce sync.Once
	file_api_user_v1_User_proto_rawDescData []byte
)

func file_api_user_v1_User_proto_rawDescGZIP() []byte {
	file_api_user_v1_User_proto_rawDescOnce.Do(func() {
		file_api_user_v1_User_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v1_User_proto_rawDesc), len(file_api_user_v1_User_proto_rawDesc)))
	})
	return file_api_user_v1_User_proto_rawDescData
}

var file_api_user_v1_User_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_user_v1_User_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: api.user.v1.RegisterRequest
	(*RegisterReply)(nil),         // 1: api.user.v1.RegisterReply
	(*BindEmailRequest)(nil),      // 2: api.user.v1.BindEmailRequest
	(*BindEmailReply)(nil),        // 3: api.user.v1.BindEmailReply
	(*BindMobileRequest)(nil),     // 4: api.user.v1.BindMobileRequest
	(*BindMobileReply)(nil),       // 5: api.user.v1.BindMobileReply
	(*IDLoginRequest)(nil),        // 6: api.user.v1.IDLoginRequest
	(*IDLoginReply)(nil),          // 7: api.user.v1.IDLoginReply
	(*GetEmailRequest)(nil),       // 8: api.user.v1.GetEmailRequest
	(*GetEmailReply)(nil),         // 9: api.user.v1.GetEmailReply
	(*GetMobileRequest)(nil),      // 10: api.user.v1.GetMobileRequest
	(*GetMobileReply)(nil),        // 11: api.user.v1.GetMobileReply
	(*DeleteRequest)(nil),         // 12: api.user.v1.DeleteRequest
	(*DeleteReply)(nil),           // 13: api.user.v1.DeleteReply
	(*UpdatePasswordRequest)(nil), // 14: api.user.v1.UpdatePasswordRequest
	(*UpdatePasswordReply)(nil),   // 15: api.user.v1.UpdatePasswordReply
	(*UpdateUsernameRequest)(nil), // 16: api.user.v1.UpdateUsernameRequest
	(*UpdateUsernameReply)(nil),   // 17: api.user.v1.UpdateUsernameReply
}
var file_api_user_v1_User_proto_depIdxs = []int32{
	0,  // 0: api.user.v1.User.Register:input_type -> api.user.v1.RegisterRequest
	2,  // 1: api.user.v1.User.BindEmail:input_type -> api.user.v1.BindEmailRequest
	4,  // 2: api.user.v1.User.BindMobile:input_type -> api.user.v1.BindMobileRequest
	6,  // 3: api.user.v1.User.IDLogin:input_type -> api.user.v1.IDLoginRequest
	8,  // 4: api.user.v1.User.GetEmail:input_type -> api.user.v1.GetEmailRequest
	10, // 5: api.user.v1.User.GetMobile:input_type -> api.user.v1.GetMobileRequest
	12, // 6: api.user.v1.User.Delete:input_type -> api.user.v1.DeleteRequest
	14, // 7: api.user.v1.User.UpdatePassword:input_type -> api.user.v1.UpdatePasswordRequest
	16, // 8: api.user.v1.User.UpdateUsername:input_type -> api.user.v1.UpdateUsernameRequest
	1,  // 9: api.user.v1.User.Register:output_type -> api.user.v1.RegisterReply
	3,  // 10: api.user.v1.User.BindEmail:output_type -> api.user.v1.BindEmailReply
	5,  // 11: api.user.v1.User.BindMobile:output_type -> api.user.v1.BindMobileReply
	7,  // 12: api.user.v1.User.IDLogin:output_type -> api.user.v1.IDLoginReply
	9,  // 13: api.user.v1.User.GetEmail:output_type -> api.user.v1.GetEmailReply
	11, // 14: api.user.v1.User.GetMobile:output_type -> api.user.v1.GetMobileReply
	13, // 15: api.user.v1.User.Delete:output_type -> api.user.v1.DeleteReply
	15, // 16: api.user.v1.User.UpdatePassword:output_type -> api.user.v1.UpdatePasswordReply
	17, // 17: api.user.v1.User.UpdateUsername:output_type -> api.user.v1.UpdateUsernameReply
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_user_v1_User_proto_init() }
func file_api_user_v1_User_proto_init() {
	if File_api_user_v1_User_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v1_User_proto_rawDesc), len(file_api_user_v1_User_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_v1_User_proto_goTypes,
		DependencyIndexes: file_api_user_v1_User_proto_depIdxs,
		MessageInfos:      file_api_user_v1_User_proto_msgTypes,
	}.Build()
	File_api_user_v1_User_proto = out.File
	file_api_user_v1_User_proto_goTypes = nil
	file_api_user_v1_User_proto_depIdxs = nil
}
