// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/email/v1/Email.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XJson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XJson) Reset() {
	*x = XJson{}
	mi := &file_api_email_v1_Email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XJson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XJson) ProtoMessage() {}

func (x *XJson) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_Email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XJson.ProtoReflect.Descriptor instead.
func (*XJson) Descriptor() ([]byte, []int) {
	return file_api_email_v1_Email_proto_rawDescGZIP(), []int{0}
}

func (x *XJson) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type CreateEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailRequest) Reset() {
	*x = CreateEmailRequest{}
	mi := &file_api_email_v1_Email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailRequest) ProtoMessage() {}

func (x *CreateEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_Email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailRequest.ProtoReflect.Descriptor instead.
func (*CreateEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_email_v1_Email_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateEmailRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailReply) Reset() {
	*x = CreateEmailReply{}
	mi := &file_api_email_v1_Email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailReply) ProtoMessage() {}

func (x *CreateEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_Email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailReply.ProtoReflect.Descriptor instead.
func (*CreateEmailReply) Descriptor() ([]byte, []int) {
	return file_api_email_v1_Email_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEmailReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateEmailTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          *XJson                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailTemplateRequest) Reset() {
	*x = CreateEmailTemplateRequest{}
	mi := &file_api_email_v1_Email_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailTemplateRequest) ProtoMessage() {}

func (x *CreateEmailTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_Email_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateEmailTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_email_v1_Email_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEmailTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEmailTemplateRequest) GetArgs() *XJson {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CreateEmailTemplateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateEmailTemplateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    uint64                 `protobuf:"varint,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailTemplateReply) Reset() {
	*x = CreateEmailTemplateReply{}
	mi := &file_api_email_v1_Email_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailTemplateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailTemplateReply) ProtoMessage() {}

func (x *CreateEmailTemplateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_Email_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailTemplateReply.ProtoReflect.Descriptor instead.
func (*CreateEmailTemplateReply) Descriptor() ([]byte, []int) {
	return file_api_email_v1_Email_proto_rawDescGZIP(), []int{4}
}

func (x *CreateEmailTemplateReply) GetTemplateId() uint64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

type SendEmailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TemplateId     uint64                 `protobuf:"varint,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	From           string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To             string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Subject        string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	UseDefaultArgs bool                   `protobuf:"varint,5,opt,name=use_default_args,json=useDefaultArgs,proto3" json:"use_default_args,omitempty"`
	Args           *XJson                 `protobuf:"bytes,6,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_api_email_v1_Email_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_Email_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_email_v1_Email_proto_rawDescGZIP(), []int{5}
}

func (x *SendEmailRequest) GetTemplateId() uint64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *SendEmailRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetUseDefaultArgs() bool {
	if x != nil {
		return x.UseDefaultArgs
	}
	return false
}

func (x *SendEmailRequest) GetArgs() *XJson {
	if x != nil {
		return x.Args
	}
	return nil
}

type SendEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailReply) Reset() {
	*x = SendEmailReply{}
	mi := &file_api_email_v1_Email_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailReply) ProtoMessage() {}

func (x *SendEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_Email_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailReply.ProtoReflect.Descriptor instead.
func (*SendEmailReply) Descriptor() ([]byte, []int) {
	return file_api_email_v1_Email_proto_rawDescGZIP(), []int{6}
}

func (x *SendEmailReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SendEmailWithTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Args          *XJson                 `protobuf:"bytes,5,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailWithTemplateRequest) Reset() {
	*x = SendEmailWithTemplateRequest{}
	mi := &file_api_email_v1_Email_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailWithTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailWithTemplateRequest) ProtoMessage() {}

func (x *SendEmailWithTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_Email_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailWithTemplateRequest.ProtoReflect.Descriptor instead.
func (*SendEmailWithTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_email_v1_Email_proto_rawDescGZIP(), []int{7}
}

func (x *SendEmailWithTemplateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendEmailWithTemplateRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendEmailWithTemplateRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailWithTemplateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailWithTemplateRequest) GetArgs() *XJson {
	if x != nil {
		return x.Args
	}
	return nil
}

type SendEmailWithTemplateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailWithTemplateReply) Reset() {
	*x = SendEmailWithTemplateReply{}
	mi := &file_api_email_v1_Email_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailWithTemplateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailWithTemplateReply) ProtoMessage() {}

func (x *SendEmailWithTemplateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_Email_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailWithTemplateReply.ProtoReflect.Descriptor instead.
func (*SendEmailWithTemplateReply) Descriptor() ([]byte, []int) {
	return file_api_email_v1_Email_proto_rawDescGZIP(), []int{8}
}

func (x *SendEmailWithTemplateReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_email_v1_Email_proto protoreflect.FileDescriptor

const file_api_email_v1_Email_proto_rawDesc = "" +
	"\n" +
	"\x18api/email/v1/Email.proto\x12\fapi.email.v1\"\x1b\n" +
	"\x05_Json\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"F\n" +
	"\x12CreateEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\",\n" +
	"\x10CreateEmailReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"s\n" +
	"\x1aCreateEmailTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04args\x18\x02 \x01(\v2\x13.api.email.v1._JsonR\x04args\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\";\n" +
	"\x18CreateEmailTemplateReply\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\x04R\n" +
	"templateId\"\xc4\x01\n" +
	"\x10SendEmailRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\x04R\n" +
	"templateId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12(\n" +
	"\x10use_default_args\x18\x05 \x01(\bR\x0euseDefaultArgs\x12'\n" +
	"\x04args\x18\x06 \x01(\v2\x13.api.email.v1._JsonR\x04args\"*\n" +
	"\x0eSendEmailReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9f\x01\n" +
	"\x1cSendEmailWithTemplateRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12'\n" +
	"\x04args\x18\x05 \x01(\v2\x13.api.email.v1._JsonR\x04args\"6\n" +
	"\x1aSendEmailWithTemplateReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xfb\x02\n" +
	"\x05Email\x12O\n" +
	"\vCreateEmail\x12 .api.email.v1.CreateEmailRequest\x1a\x1e.api.email.v1.CreateEmailReply\x12g\n" +
	"\x13CreateEmailTemplate\x12(.api.email.v1.CreateEmailTemplateRequest\x1a&.api.email.v1.CreateEmailTemplateReply\x12I\n" +
	"\tSendEmail\x12\x1e.api.email.v1.SendEmailRequest\x1a\x1c.api.email.v1.SendEmailReply\x12m\n" +
	"\x15SendEmailWithTemplate\x12*.api.email.v1.SendEmailWithTemplateRequest\x1a(.api.email.v1.SendEmailWithTemplateReplyB'\n" +
	"\fapi.email.v1P\x01Z\x15email/api/email/v1;v1b\x06proto3"

var (
	file_api_email_v1_Email_proto_rawDescOnce sync.Once
	file_api_email_v1_Email_proto_rawDescData []byte
)

func file_api_email_v1_Email_proto_rawDescGZIP() []byte {
	file_api_email_v1_Email_proto_rawDescOnce.Do(func() {
		file_api_email_v1_Email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_email_v1_Email_proto_rawDesc), len(file_api_email_v1_Email_proto_rawDesc)))
	})
	return file_api_email_v1_Email_proto_rawDescData
}

var file_api_email_v1_Email_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_email_v1_Email_proto_goTypes = []any{
	(*XJson)(nil),                        // 0: api.email.v1._Json
	(*CreateEmailRequest)(nil),           // 1: api.email.v1.CreateEmailRequest
	(*CreateEmailReply)(nil),             // 2: api.email.v1.CreateEmailReply
	(*CreateEmailTemplateRequest)(nil),   // 3: api.email.v1.CreateEmailTemplateRequest
	(*CreateEmailTemplateReply)(nil),     // 4: api.email.v1.CreateEmailTemplateReply
	(*SendEmailRequest)(nil),             // 5: api.email.v1.SendEmailRequest
	(*SendEmailReply)(nil),               // 6: api.email.v1.SendEmailReply
	(*SendEmailWithTemplateRequest)(nil), // 7: api.email.v1.SendEmailWithTemplateRequest
	(*SendEmailWithTemplateReply)(nil),   // 8: api.email.v1.SendEmailWithTemplateReply
}
var file_api_email_v1_Email_proto_depIdxs = []int32{
	0, // 0: api.email.v1.CreateEmailTemplateRequest.args:type_name -> api.email.v1._Json
	0, // 1: api.email.v1.SendEmailRequest.args:type_name -> api.email.v1._Json
	0, // 2: api.email.v1.SendEmailWithTemplateRequest.args:type_name -> api.email.v1._Json
	1, // 3: api.email.v1.Email.CreateEmail:input_type -> api.email.v1.CreateEmailRequest
	3, // 4: api.email.v1.Email.CreateEmailTemplate:input_type -> api.email.v1.CreateEmailTemplateRequest
	5, // 5: api.email.v1.Email.SendEmail:input_type -> api.email.v1.SendEmailRequest
	7, // 6: api.email.v1.Email.SendEmailWithTemplate:input_type -> api.email.v1.SendEmailWithTemplateRequest
	2, // 7: api.email.v1.Email.CreateEmail:output_type -> api.email.v1.CreateEmailReply
	4, // 8: api.email.v1.Email.CreateEmailTemplate:output_type -> api.email.v1.CreateEmailTemplateReply
	6, // 9: api.email.v1.Email.SendEmail:output_type -> api.email.v1.SendEmailReply
	8, // 10: api.email.v1.Email.SendEmailWithTemplate:output_type -> api.email.v1.SendEmailWithTemplateReply
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_email_v1_Email_proto_init() }
func file_api_email_v1_Email_proto_init() {
	if File_api_email_v1_Email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_email_v1_Email_proto_rawDesc), len(file_api_email_v1_Email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_email_v1_Email_proto_goTypes,
		DependencyIndexes: file_api_email_v1_Email_proto_depIdxs,
		MessageInfos:      file_api_email_v1_Email_proto_msgTypes,
	}.Build()
	File_api_email_v1_Email_proto = out.File
	file_api_email_v1_Email_proto_goTypes = nil
	file_api_email_v1_Email_proto_depIdxs = nil
}
